// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrIrGrvxQJd2bSAbwDmA8AZ4SeaaKMC0',
    appId: '1:55421304368:web:4a94ba21d45f1b219e77f5',
    messagingSenderId: '55421304368',
    projectId: 'findit-8d40d',
    authDomain: 'findit-8d40d.firebaseapp.com',
    storageBucket: 'findit-8d40d.firebasestorage.app',
    measurementId: 'G-XSJHBYS8QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtzEF-W0irgMmr5NtSHZ9NLgavjjiTeQ',
    appId: '1:55421304368:android:d2db26f147147d3b9e77f5',
    messagingSenderId: '55421304368',
    projectId: 'findit-8d40d',
    storageBucket: 'findit-8d40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAbBmiB0d2OFmAu_UXuxv5FYIi4oXAf0c',
    appId: '1:55421304368:ios:97cd08c5ff3f1d5a9e77f5',
    messagingSenderId: '55421304368',
    projectId: 'findit-8d40d',
    storageBucket: 'findit-8d40d.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAbBmiB0d2OFmAu_UXuxv5FYIi4oXAf0c',
    appId: '1:55421304368:ios:97cd08c5ff3f1d5a9e77f5',
    messagingSenderId: '55421304368',
    projectId: 'findit-8d40d',
    storageBucket: 'findit-8d40d.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYrIrGrvxQJd2bSAbwDmA8AZ4SeaaKMC0',
    appId: '1:55421304368:web:5d804a612501b6ec9e77f5',
    messagingSenderId: '55421304368',
    projectId: 'findit-8d40d',
    authDomain: 'findit-8d40d.firebaseapp.com',
    storageBucket: 'findit-8d40d.firebasestorage.app',
    measurementId: 'G-1RGRDHDHZ0',
  );
}
